/*
 * NPLL - SoC hardware block address map
 *
 * Copyright (C) 2026 Techflash
 */

#ifndef _SOC_H
#define _SOC_H

#include <npll/utils.h>

/* Flipper MMIO bus */
#define FLIPPER_CP_OFFSET      0x000000
#define FLIPPER_PE_OFFSET      0x001000
#define FLIPPER_VI_OFFSET      0x002000
#define FLIPPER_PI_OFFSET      0x003000
#define FLIPPER_MI_OFFSET      0x004000
#define FLIPPER_DSP_OFFSET     0x005000
#define FLIPPER_DI_OFFSET      0x006000
#define FLIPPER_SI_OFFSET      0x006400
#define FLIPPER_EXI_OFFSET     0x006800
#define FLIPPER_AI_OFFSET      0x006c00
#define FLIPPER_GX_FIFO_OFFSET 0x008000

#define FLIPPER_CP_BASE      (FLIPPER_MMIO_BASE + FLIPPER_CP_OFFSET)
#define FLIPPER_PE_BASE      (FLIPPER_MMIO_BASE + FLIPPER_PE_OFFSET)
#define FLIPPER_VI_BASE      (FLIPPER_MMIO_BASE + FLIPPER_VI_OFFSET)
#define FLIPPER_PI_BASE      (FLIPPER_MMIO_BASE + FLIPPER_PI_OFFSET)
#define FLIPPER_MI_BASE      (FLIPPER_MMIO_BASE + FLIPPER_MI_OFFSET)
#define FLIPPER_DSP_BASE     (FLIPPER_MMIO_BASE + FLIPPER_DSP_OFFSET)
#define FLIPPER_DI_BASE      (FLIPPER_MMIO_BASE + FLIPPER_DI_OFFSET)
#define FLIPPER_SI_BASE      (FLIPPER_MMIO_BASE + FLIPPER_SI_OFFSET)
#define FLIPPER_EXI_BASE     (FLIPPER_MMIO_BASE + FLIPPER_EXI_OFFSET)
#define FLIPPER_AI_BASE      (FLIPPER_MMIO_BASE + FLIPPER_AI_OFFSET)
#define FLIPPER_GX_FIFO_BASE (FLIPPER_MMIO_BASE + FLIPPER_GX_FIFO_OFFSET)

/* Latte hardware on the Flipper MMIO bus */
#define LATTE_PI_OFFSET   FLIPPER_CP_OFFSET
#define LATTE_R600_OFFSET 0x200000

#define LATTE_PI_BASE   (FLIPPER_MMIO_BASE + LATTE_PI_OFFSET)
#define LATTE_R600_BASE (FLIPPER_MMIO_BASE + LATTE_R600_OFFSET)

/* Hollywood and Latte AHB */
#define HOLLYWOOD_REGS_OFFSET    0x000000
#define LATTE_REGS_OFFSET        0x000400
#define HOLLYWOOD_DI_OFFSET      0x006000
#define HOLLYWOOD_SI_OFFSET      0x006400
#define HOLLYWOOD_EXI_OFFSET     0x006800
#define HOLLYWOOD_NAND_OFFSET    0x010000
#define HOLLYWOOD_AES_OFFSET     0x020000
#define HOLLYWOOD_SHA1_OFFSET    0x030000
#define HOLLYWOOD_EHCI0_OFFSET   0x040000
#define HOLLYWOOD_OHCI0_OFFSET   0x050000
#define HOLLYWOOD_OHCI1_OFFSET   0x060000
#define HOLLYWOOD_SDHC0_OFFSET   0x070000
#define HOLLYWOOD_SDHC1_OFFSET   0x080000
#define HOLLYWOOD_MEMCTRL_OFFSET 0x0b4200
#define LATTE_SDHC2_OFFSET       0x100000
#define LATTE_SDHC3_OFFSET       0x110000
#define LATTE_EHCI1_OFFSET       0x120000
#define LATTE_EHCI2_OFFSET       0x140000

#define HOLLYWOOD_REGS_BASE    (AHB_BASE + HOLLYWOOD_REGS_OFFSET)
#define LATTE_REGS_BASE        (AHB_BASE + LATTE_REGS_OFFSET)
#define HOLLYWOOD_DI_BASE      (AHB_BASE + HOLLYWOOD_DI_OFFSET)
#define HOLLYWOOD_SI_BASE      (AHB_BASE + HOLLYWOOD_SI_OFFSET)
#define HOLLYWOOD_EXI_BASE     (AHB_BASE + HOLLYWOOD_EXI_OFFSET)
#define HOLLYWOOD_NAND_BASE    (AHB_BASE + HOLLYWOOD_NAND_OFFSET)
#define HOLLYWOOD_AES_BASE     (AHB_BASE + HOLLYWOOD_AES_OFFSET)
#define HOLLYWOOD_SHA1_BASE    (AHB_BASE + HOLLYWOOD_SHA1_OFFSET)
#define HOLLYWOOD_EHCI0_BASE   (AHB_BASE + HOLLYWOOD_EHCI0_OFFSET)
#define HOLLYWOOD_OHCI0_BASE   (AHB_BASE + HOLLYWOOD_OHCI0_OFFSET)
#define HOLLYWOOD_OHCI1_BASE   (AHB_BASE + HOLLYWOOD_OHCI1_OFFSET)
#define HOLLYWOOD_SDHC0_BASE   (AHB_BASE + HOLLYWOOD_SDHC0_OFFSET)
#define HOLLYWOOD_SDHC1_BASE   (AHB_BASE + HOLLYWOOD_SDHC1_OFFSET)
#define HOLLYWOOD_MEMCTRL_BASE (AHB_BASE + HOLLYWOOD_MEMCTRL_OFFSET)
#define LATTE_SDHC2_BASE       (AHB_BASE + LATTE_SDHC2_OFFSET)
#define LATTE_SDHC3_BASE       (AHB_BASE + LATTE_SDHC3_OFFSET)
#define LATTE_EHCI1_BASE       (AHB_BASE + LATTE_EHCI1_OFFSET)
#define LATTE_EHCI2_BASE       (AHB_BASE + LATTE_EHCI2_OFFSET)

#endif /* _SOC_H */
